- client/components/CompleteProfile.tsx
- client/routes/Onboarding.tsx
- client/routes/RouteHandlers.tsx
- server/routes/stripe.ts
- types/express.d.ts
Also fixed an issue with custom onboarding where we were checking for `custom`, however the newly created accounts are not custom.
The UX is not impacted.
> Specify a value for external_account_collection

- package.json
- server/routes/stripe.ts
- yarn.lock
This PR pulls in the latest `stripe` package version 15.5.0-beta.1 in order to support the `payment_method_settings` component. It also removes the TS hack that was necessary to include the component before this.
> Use the beta SDK for the payment_method_settings component

- app/components/AuthenticatedAndOnboardedRoute.tsx
- app/components/AuthenticatedRoute.tsx
Fixes a bug that caused redirects to `/home` after a manual refresh of the page
> Fix bug that causes wrong redirect

- client/hooks/ConnectJsWrapper.tsx
- client/routes/Onboarding.tsx
- server/routes/stripe.ts
We'll be pushing a change soon to block creating account sessions for components like `financial` account if the account does not have access to the corresponding capability. 
This change should prevent 400s from showing up.
> Only request Issuing + Treasury components if those capabilities exist

- app/(dashboard)/finances/page.tsx
- app/api/account_session/route.ts
Same as #142 but for the redesign. Much easier to reason about here as the page already does a full reload.
> Only request Issuing + Treasury components if those capabilities exist in redesign

- app/api/payment_method_settings/create_checkout_session/route.ts
- app/api/setup_accounts/create_risk_intervention/route.ts
- app/components/ToolsPanel.tsx
- app/components/testdata/CreateCheckoutSessionButton.tsx
When trying out the embedded payment method settings component, it's important for the user to be able to quickly launch into Checkout so that they can see how these payment methods are presented to buyers. This PR introduces a "Create Checkout Session" button to the Tools panel on the settings page. Users can specify the following parameters:
* Amount (defaults to a random number between `4000` and `12000`)
* Currency (defaults to the merchant's default currency)
https://github.com/stripe/stripe-connect-furever-demo/assets/95376121/cd1b9592-76a6-4327-b033-8468e779afe1
Tools panel:
Create Checkout Session dialog:
Launching a Checkout session with amount and currency filled:
> Add a Tools button to create Checkout sessions from the account settings page

- app/api/debug/create_checkout_session/route.ts
- app/api/payment_method_settings/create_checkout_session/route.ts
We were populating redirect URLs from a nonexistent env variable which causes the Stripe API to return 400s when we tried to create Checkout sessions in production. This PR changes the two affected callsites to use `$NEXTAUTH_URL` which _is_ populated in both dev and prod. This fixes two actions that were broken in prod:
* `create_checkout_session` debug command (cmd+shift+k)
* `create_checkout_session` API on the account settings page
> Fix redirect URLs when creating checkout sessions

- app/components/Screen.tsx
- components/ui/dialog.tsx
| Before | After |
| --- | --- |
| ![CleanShot 2024-06-18 at 16 41 29](https://github.com/stripe/stripe-connect-furever-demo/assets/99840257/5a402b47-006b-4ac9-a09d-1cdb3a83357a) | ![CleanShot 2024-06-18 at 16 41 12](https://github.com/stripe/stripe-connect-furever-demo/assets/99840257/c1e04faf-d297-4ef8-ad18-1f2122d5c164) |
> Fix z-index issue

- app/api/account_session/route.ts
- package.json
- yarn.lock
External account collection should be off for custom accounts, this specifies the parameter in account session to be false. Now custom users do not have to authenticate or claim their account to see account management
https://github.com/user-attachments/assets/11cd1625-ab9e-4a4b-8066-be8cc895c9aa
> Turn external account collection off for custom accounts

- app/(auth)/business/form.tsx
- app/api/account_session/route.ts
- app/api/setup_accounts/route.ts
- app/components/QuickstartButton.tsx
- lib/auth.ts
- types/account.ts
Disputes now have a customer
Business name and type are prefilled if they are specified:
Individual (taken straight to identity info page):
https://github.com/user-attachments/assets/b32e74af-db84-4c13-b764-a118f349055f
Other (have to pick)
https://github.com/user-attachments/assets/7f845753-d4b0-446d-a8bd-a88896b6e6da
Also tested with company but did not screen record
> Prefill with business name and type if they exist, change email domains

- types/account.ts
Remove Indonesia from the list of country options in the business sign up page. Only Indonesian platforms can create Indonesian accounts, so selecting Indonesia on Furever would cause an error.
https://github.com/user-attachments/assets/12ac66e5-0365-458e-80fc-d2c61ff3c2a5
> Remove Indonesia from country list

- app/api/setup_accounts/create_charges/route.ts
Fixing the url for https://docs.stripe.com/payments/place-a-hold-on-a-payment-method
> Fix payment capture docs url

- app/(auth)/login/form.tsx
- app/(auth)/signup/form.tsx
Previously you could log in with bad credentials as the code path would always redirect you to `/home`. Now you're prevented!
Also, we didn't check for errors when you attempted to sign up with an email that is already in use.
> Show form error if login credentials are incorrect

- app/api/account_session/route.ts
We'll be adding validation to ensure the disable_stripe_user_authentication feature is enabled or disabled across all components. We should explicitly enable this feature to match with the other components that take in the feature (i.e. only enable it for custom CAs).
Tested this locally and verified the components load as expected.
> Add disable_stripe_user_authentication to Issuing Cards List component

- app/(dashboard)/finances/page.tsx
- app/api/account_session/route.ts
- app/components/EmbeddedComponentContainer.tsx
Switch the old CapitalOverview embedded component to the new CapitalFinancingPromotion embedded component. This new embedded component will display details of a financing offer for the account if there is one.
> Adding the new CapitalFinancingPromotion component

- app/(dashboard)/settings/layout.tsx
- app/api/login_link/route.ts
- app/hooks/useExpressDashboardLoginLink.tsx
When merchant has express dashboard access, display link to open express dashboard
https://github.com/user-attachments/assets/86b48b4c-8e2b-482f-819f-da0642a4e492
> Add express login link to furever

- app/(dashboard)/finances/financing/page.tsx
- app/(dashboard)/home/page.tsx
- app/components/CapitalFinancingPromotionSection.tsx
Current behavior
- There is a capital financing fullsize promotion on Finances->Financing page
New behavior
- There is an XS Capital promo tile on homepage if a Capital offer is available
See screenshots for new behavior:
no offer state
offer state
Refactoring; no changes to Financing page itself:
> [capital-for-platforms] Add XS promo tile to homepage if Capital offer is available

- app/(auth)/login/form.tsx
- app/(auth)/signup/form.tsx
- lib/forms.ts
The form for register and sign in both are the same fields. This centralizes them, and uses the same errors:
> Improve the errors of the forms

- app/(auth)/business/form.tsx
This makes it so there's an error message if the business name isn't provided or is too short.
> Improve validation of the business name field

- app/(dashboard)/settings/tax/page.tsx
- app/api/account_session/route.ts
- package.json
- yarn.lock
Add export tax transactions embedded component; Bump stripe package version.
Already added the account (`acct_1KgGJqGxJ4qxTuYt`) to the gate enabling this component.
Tested locally:
> Add export tax transactions embedded component

- app/api/capital/approve_test_financing/route.ts
- app/api/capital/create_test_financing/route.ts
- app/api/capital/expire_test_financing/route.ts
- app/api/capital/fully_repay_test_financing/route.ts
- app/api/capital/get_financing_offer/route.ts
- app/api/capital/reject_test_financing/route.ts
- app/components/ToolsPanel.tsx
- app/components/testdata/Financing/CreateFlexLoanButton.tsx
- app/components/testdata/Financing/ManageFinancing.tsx
- app/components/testdata/Financing/TransitionFinancingButton.tsx
- app/components/testdata/Financing/types.ts
This adds buttons to the tool panel:
- Create a Flex Loan Offer in a certain state
- Expire a delivered offer
- Approve/Reject an accepted offer
- Fully repay a paid out offer
The buttons are shown when the connected account has a financing offer in a certain state or does not have a financing state at all.
Screen Recording:
https://github.com/user-attachments/assets/83ce911d-8d2d-4f10-a51b-9be2d5d76620
[Edit]
Screen Recording as of 33febfd
https://github.com/user-attachments/assets/ff0bfccf-b4d0-436a-89e6-0c95d7b99655
> Add Capital Financing Buttons to Tools Panel to Manipulate Financing Offer States

- app/components/testdata/Financing/CreateFlexLoanButton.tsx
- app/components/testdata/Financing/ManageFinancing.tsx
- Right align select componet
- Make select field `text-xs`
- Remove `Capital` header in Tools Panel
> UX changes to Capital helpers in Tools Panels

- app/api/capital/create_test_financing/route.ts
- app/components/testdata/Financing/CreateFlexLoanButton.tsx
- app/components/testdata/Financing/ManageFinancing.tsx
- Increase test financing offer size so that the offer application shows a slider. In the future, we might make this a configurable option in the frontend
- Fix dropdown bug in the `Create flex loan` helper where you could not select the default option `Delivered` after selecting another option. Setting the Radix form's default value caused some contention and removing it fixed it.
> Increase Financing offer size to show slider and fix dropdown bug
