app/(dashboard)/home/page.tsx
app/(dashboard)/settings/page.tsx
app/api/account_session/route.ts

Adding the notification banner to homepage, there is a bit of a weird border, will fast follow to try to get rid of it

Add notification banner

---

app/(dashboard)/payments/page.tsx
app/(dashboard)/payouts/page.tsx
app/(dashboard)/settings/page.tsx
app/api/account_session/route.ts
app/api/setup_accounts/create_risk_intervention/route.ts
app/page.tsx
components/ui/form.tsx

This PR 
-  enables capital component in account session claim
- Adds notification banner to settings as well
- Adds create risk intervention button
https://github.com/stripe/stripe-connect-furever-demo/assets/124314569/62a1b515-7999-4cc1-95d6-862fdfc0e0e9

Add demo risk intervention button, enable capital

---

README.md
app/(dashboard)/finances/page.tsx
app/api/account_session/route.ts
app/api/request_capabilities/route.ts
app/components/Nav.tsx

This PR 
- adds the treasury and issuing and capital components
- updates readme
- 
https://github.com/stripe/stripe-connect-furever-demo/assets/124314569/7ba625dc-ea85-422a-b656-79e52637c2ff

Enable baas components

---

app/(dashboard)/home/page.tsx
app/(dashboard)/payments/page.tsx
app/(dashboard)/payouts/page.tsx
app/(dashboard)/settings/page.tsx
app/components/BalanceWidget.tsx
app/components/CustomersWidget.tsx
app/components/MonthToDateWidget.tsx
app/components/RecentPaymentsWidget.tsx
app/components/Schedule.tsx

* make `/home` more responsive
* spacing fixes

More polish fixes

---

app/(auth)/layout.tsx
app/(dashboard)/finances/layout.tsx
app/(dashboard)/home/page.tsx
app/(dashboard)/layout.tsx
app/(dashboard)/payments/page.tsx
app/(dashboard)/pets/page.tsx
app/(dashboard)/settings/layout.tsx
app/(dashboard)/settings/page.tsx
app/components/CustomersWidget.tsx
app/components/MonthToDateWidget.tsx
app/components/Nav.tsx
app/components/Schedule.tsx
app/page.tsx

Makes the redesigned site mobile-friendly. Implements a simple mobile hamburger menu from the existing navigation.
| Home  | Sign up | Menu |
| ------------- | ------------- | ------------- |
| ![CleanShot 2024-05-13 at 01 08 14](https://github.com/stripe/stripe-connect-furever-demo/assets/99840257/5d3faa4f-d045-4097-8219-2fe9e32bb7ce) | ![CleanShot 2024-05-13 at 01 08 24](https://github.com/stripe/stripe-connect-furever-demo/assets/99840257/3ef5a42b-ddb6-4820-84ef-1eb4a0f7532f) | ![CleanShot 2024-05-13 at 01 07 15](https://github.com/stripe/stripe-connect-furever-demo/assets/99840257/e44a7101-7c25-4164-b551-223001f22cef) |
| Payments | Payouts | Settings |
| ------------- | ------------- | ------------- |
| ![CleanShot 2024-05-13 at 01 07 …

Responsive design

---

app/components/Container.tsx
app/components/Nav.tsx
components/ui/switch.tsx
package.json
yarn.lock

Add a toggle to turn on or off component borders
https://github.com/stripe/stripe-connect-furever-demo/assets/124314569/22d53523-b198-4211-bd27-ba5775d55331

Add a toggle for component borders

---

app/(dashboard)/layout.tsx
app/components/Nav.tsx

* Updates the component outline switch at the bottom of the screen on mobile devices

Polish component outline switch for mobile

---

app/(dashboard)/home/page.tsx
app/(dashboard)/layout.tsx
app/components/Container.tsx
app/components/EmbeddedComponentContainer.tsx
app/components/OnboardingDialog.tsx
app/components/Schedule.tsx

* Fixed bug that showed NUX repeatedly after page refresh
* Fixed spacing issue with notification banner
| Mobile | Desktop |
| --- | --- |
| ![CleanShot 2024-05-14 at 20 35 30](https://github.com/stripe/stripe-connect-furever-demo/assets/99840257/ee91518e-75d7-4ac8-a1ba-74fb5c828dce) | ![CleanShot 2024-05-14 at 20 30 56](https://github.com/stripe/stripe-connect-furever-demo/assets/99840257/540828b1-db8a-4491-a387-c5c1fd877de3) |

Fix onboarding and notification banner bugs

---

app/components/Nav.tsx
app/components/Screen.tsx
app/components/Tools/LocaleSelector.tsx
app/components/ToolsPanel.tsx
app/components/testdata/CreateFinancialCreditButton.tsx
app/components/testdata/CreateInterventionsButton.tsx
app/components/testdata/CreatePaymentsButton.tsx
app/components/testdata/CreatePayoutsButton.tsx

See video
https://github.com/stripe/stripe-connect-furever-demo/assets/99840257/b9e7c3ad-7e15-4a18-a2f3-86330f8c3324

Polish tools panel animation and make responsive

---

app/components/Nav.tsx
app/components/Screen.tsx
app/page.tsx
components/ui/button.tsx
components/ui/dialog.tsx

Fixed some z-index and mobile bugs

Fix bugs with tools panel responsiveness

---

app/(auth)/layout.tsx
app/components/OnboardingDialog.tsx
app/components/testdata/CreateCheckoutSessionButton.tsx
app/components/testdata/CreateFinancialCreditButton.tsx
app/components/testdata/CreateInterventionsButton.tsx
app/components/testdata/CreatePaymentsButton.tsx
app/contexts/settings/SettingsProvider.tsx
components/ui/button.tsx
components/ui/input.tsx

Fixes bug on homepage that incorrectly shows dark mode
Before:

Fix homepage dark mode bug

---

app/components/Screen.tsx
app/components/testdata/CreateCheckoutSessionButton.tsx
app/components/testdata/CreatePaymentsButton.tsx

Before:
https://github.com/stripe/stripe-connect-furever-demo/assets/99840257/7a327a92-e583-4b21-8757-67311933d5e0
After:
https://github.com/stripe/stripe-connect-furever-demo/assets/99840257/948d0946-cdec-48ba-9d65-8ff3d40000aa

Fix input focus bug

---

app/api/account_session/route.ts

Financial account should also enable the EAC feature

Align features requested for financial account

---

app/(dashboard)/billing/page.tsx
app/(dashboard)/layout.tsx
app/api/subscriptions/route.ts
app/components/SubscriptionNextBillWidget.tsx
app/components/SubscriptionPortalWidget.tsx
app/components/SubscriptionsBanner.tsx
package.json
yarn.lock

Added a page to manage your billing subscriptions

Added subscription management page

---

app/(dashboard)/billing/page.tsx
app/api/customer_portal/route.ts
app/components/EmbeddedComponentContainer.tsx
app/components/SubscriptionNextBillWidget.tsx
app/components/SubscriptionPortalWidget.tsx

Adds support for customer portal for existing subscriptions
https://github.com/user-attachments/assets/56c62f36-0bea-4d88-b4c3-1b9ad015541d
Also adds in the border outline for the pricing table:

Implement support for customer portal

---

app/api/customer_portal/route.ts

To merge in once we update the CNAME

Update route.ts with new URL

---

lib/auth.ts

Use slightly different strings from https://docs.stripe.com/connect/testing
This will do more synchronous checks against the account, instead of async verifications.

Use sync verifications for information

---

package.json
yarn.lock

Bump version of react-connect-js

---

app/(auth)/login/form.tsx
app/page.tsx

Adding data test ids for use in synthetics testing

Adding data test ids to components

---

app/(auth)/layout.tsx
app/api/company_name/route.ts
app/components/BrandSettingsModal.tsx
app/components/CustomersWidget.tsx
app/components/MonthToDateWidget.tsx
app/components/Nav.tsx
app/components/Screen.tsx
lib/utils.ts
tailwind.config.ts

1. Changes the lines on the mock graphs to better respond to the primary color
2. Remove "Pets" from the sidebar and the paw print background when any brand settings are set
3. Adds a reset button
https://github.com/user-attachments/assets/4a2013b1-a1d9-4808-a7c4-5c1270968a26

Brand settings tweaks

---

yarn.lock

Tested onboarding after making this change

Update yarn.lock (keep dependencies in package.json accurate with yarnlock)
